---
- hosts: 
    - instructserver
  remote_user: ubuntu
  environment:
    S3_URL: http://3.20.186.233:9000
    S3_ACCESS_KEY: minioproject
    S3_SECRET_KEY: instructproject
  roles:
    - project
    - minio
    - gunicorn
