---
- hosts: 
    - myserver
  remote_user: root
  environment:
    S3_URL: http://172.107.46.232:9000
    S3_ACCESS_KEY: minioproject
    S3_SECRET_KEY: instructproject
  roles:
    - project
    - minio
    - gunicorn