---
- name: updating apt repo and installing packages
  apt: 
    pkg:
      - python3
      - python3-pip
      - gunicorn
      - unzip
    state: latest
    update_cache: yes
  become: yes

- name: installing pipenv
  pip:
    name: 
      - pipenv
      - black
    state: latest
  become: yes

- name: stat folder
  stat:
    path: "{{project_dir}}"
  register: path_exist

- git:
    repo: git@gitlab.com:thaygneel/minio-uploader.git
    dest: "{{project_dir}}"
    accept_hostkey: yes

  when: not path_exist.stat.exists

- name: Run a pipenv install
  command: pipenv --python 3 install --system --deploy
  args:
    chdir: "{{ project_dir }}"

